---
- name: Ansible needs some packages
  apt: pkg={{ item }}
  with_items:
      - python-pycurl
- name: debian backport
  apt_repository: repo='deb http://ftp.fr.debian.org/debian wheezy-backports main' state=present
- name: refresh repository
  apt: cache_valid_time=3600
       update_cache=yes

- name: A user for iPython
  user: name=ipython

- name: iPython needs some packages
  apt: pkg={{ item }}
  with_items:
      - python-virtualenv
      - python-dev

- name: Modern pip
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name={{ item.name }}
       version={{ item.version }}
  with_items:
   - name: pip
     version: 1.5.4
   - name: distribute
     version: 0.7.3

- name: pip install iPython
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name=ipython

- name: Profile folder
  command: sudo -u ipython /home/ipython/bin/ipython profile create web
           creates=/home/ipython/.ipython/profile_web/ipython_notebook_config.py

- name: iPython config
  template: src=ipython_config.py.j2
            dest=/home/ipython/.ipython/profile_web/ipython_config.py
            owner=ipython
  #notify: restart ipython

