---
- name: Ansible needs some packages
  apt: pkg={{ item }}
  with_items:
      - python-pycurl
- name: debian backport
  apt_repository: repo='deb http://ftp.fr.debian.org/debian wheezy-backports main' state=present
- name: refresh repository
  apt: cache_valid_time=3600
       update_cache=yes

- name: install special version of Nginx
  apt: pkg=nginx
       default_release=wheezy-backports
       state=present
- name: Log folder for iPython nginx vhost
  file: state=directory path=/var/log/nginx/{{ ipython_domain }} owner=www-data
- name: iPython vhost Nginx available
  template: src=ipython.nginx.j2 dest=/etc/nginx/sites-available/ipython
  notify: restart nginx
- name: iPython vhost Nginx enabled
  file: state=link src=/etc/nginx/sites-available/ipython dest=/etc/nginx/sites-enabled/ipython
  notify: restart nginx
- name: Nginx is started
  service: name=nginx state=started
