---
notebook_password: plop
notebook_interface: eth0

numpy_version:      1.9.1
openblas_version:   0.2.8
lapack_version:     3.5.0
scipy_version:      0.14.0
numexpr_version:    2.4
blaze_version:      0.6.5
pandas_version:     0.15.0
sklearn_version:    0.15.2
matplotlib_version: 1.4.1
rocksdb_version:    rocksdb-3.6.2
pyrocksdb_version:  0.2.1


ipython_pandas:   false
ipython_scipy:    false
ipython_learnkit: false
ipython_numba:    false
ipython_theano:   false
ipython_numexpr:  false
ipython_imagesk:  false
ipython_blz:      false
ipython_pymc:     false
ipython_rockdb:   false
