---
- name: iPython needs some packages
  apt: pkg={{ item }}
  with_items:
      - supervisor
      - libzmq3-dev
      - libfreetype6-dev
      - libpng12-dev

- name: Scipy needs some packages
  apt: pkg={{ item }}
  with_items:
      # Scipy
      - gfortran
      - libblas-dev
      - liblapack-dev
      - libatlas-dev
  when: ipython_scipy

- name: ipython requirements
  template: src=requirements.txt.j2 dest=/home/ipython/requirements.txt

- name: installing ipython
  pip: chdir=/home/ipython
       requirements=requirements.txt
       virtualenv=/home/ipython

- name: Notebooks password
  command: /home/ipython/bin/python -c "from IPython.lib import passwd; print passwd('{{ notebook_password }}', algorithm='sha512')"
  register: notebooks_hash

- name: Notebooks folder
  file: path=/home/ipython/notebooks state=directory owner=ipython

- name: Profile folder
  command: sudo -u ipython /home/ipython/bin/ipython profile create web
           creates=/home/ipython/.ipython/profile_web/ipython_notebook_config.py

- name: iPython notebooks config
  template: src=ipython_notebook_config.py.j2
            dest=/home/ipython/.ipython/profile_web/ipython_notebook_config.py
            owner=ipython
  notify: restart ipython

- name: iPython config
  template: src=ipython_config.py.j2
            dest=/home/ipython/.ipython/profile_web/ipython_config.py
            owner=ipython
  notify: restart ipython

- name: supervisor is startd
  service: name=supervisor state=started
- name: iPython supervisor conf
  template: src=ipython.supervisord.conf.j2 dest=/etc/supervisor/conf.d/ipython.conf
  notify: restart ipython
- name: reload supervisor
  command: supervisorctl reload
