---
- name: iPython needs some packages
  apt: pkg={{ item }}
  with_items:
      - libfreetype6-dev
      - libpng12-dev

- name: Scipy needs some packages
  apt: pkg={{ item }}
  with_items:
      # Scipy
      - gfortran
      - libblas-dev
      - liblapack-dev
      - libatlas-dev
  when: ipython_scipy

- name: ipython requirements
  template: src=requirements.txt.j2 dest=/home/ipython/requirements.txt

- name: installing ipython
  pip: chdir=/home/ipython
       requirements=requirements.txt
       virtualenv=/home/ipython

