---
- name: iPython needs some packages
  apt: pkg={{ item }}
  with_items:
      - libfreetype6-dev
      - libpng12-dev

- name: Scipy needs some packages
  apt: pkg={{ item }}
  with_items:
      # Scipy
      - gfortran
      - libblas-dev
      - libopenblas-dev
      - liblapack-dev
      - libatlas-dev
  when: ipython_scipy

- name: ipython requirements
  template: src=requirements.txt.j2 dest=/home/ipython/requirements.txt

- name: Clean build folder
  file: path=/home/ipython/build
        state=absent

- name: installing ipython
  pip: chdir=/home/ipython
       requirements=requirements.txt
       virtualenv=/home/ipython

- name: installing numpy
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name=numpy

- name: installing matplotlib
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name=matplotlib

- name: installing scipy
  when: ipython_scipy or ipython_pandas or ipython_learnkit or ipython_theano
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name=scipy

- name: installing pandas
  when: ipython_pandas
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name=pandas

- name: Installing Scikit-Learn
  when: ipython_learnkit
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name=scikit-learn

- name: Installing Numba
  when: ipython_numba
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name=numba

- name: Installing Theano
  when: ipython_theano
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name=theano

- name: Installing Numexpr
  when: ipython_numexpr
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name=numexpr

- name: Installing Scikit-Image
  when: ipython_imagesk
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name={{ item}}
  with_items:
      - cython
      - pillow
      - scikit-image

- name: Installing BLZ
  when: ipython_blz
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name=blz

- name: Installing PyMC
  when: ipython_pymc
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name=pymc

# Tables deps
# libhdf5-dev

# MPI deps
# openmpi deps
# libopenmpi-dev
# openmpi-bin


# disco deps
# git
# libcmph-dev
#
# https://github.com/discoproject/disco/archive/0.5.1.tar.gz
