---
- name: iPython needs some packages
  apt: pkg={{ item }}
  with_items:
      - libfreetype6-dev
      - libpng12-dev
      - gfortran
      - git

- name: OpenBLAS
  git: version=v0.2.8
       repo=https://github.com/xianyi/OpenBLAS.git
       dest=/home/ipython/src/OpenBLAS

- name: make OpenBLAS
  command: make FC=gfortran
           chdir=/home/ipython/src/OpenBLAS
           creates=libopenblas.so

- name: install OpenBLAS
  command: make PREFIX=/usr/local NO_CBLAS=1 NO_LAPACK=1 install
           chdir=/home/ipython/src/OpenBLAS
           creates=/usr/local/lib/libopenblas.so

- name: ldconfig OpenBLAS
  command: ldconfig
           chdir=/home/ipython/src/OpenBLAS

- name: CBLAS sources
  get_url: url=http://www.netlib.org/blas/blast-forum/cblas.tgz
           dest=/home/ipython/src

- name: Decompress CBLAS
  command: tar -xvzf cblas.tgz
           chdir=/home/ipython/src/
           creates=/home/ipython/src/CBLAS

- name: Configure CBLAS
  copy: src=CBLAS-Makefile.in
        dest=/home/ipython/src/CBLAS/Makefile.in

- name: make CBLAS
  command: make
           chdir=/home/ipython/src/CBLAS
           creates=/home/ipython/src/CBLAS/lib/libcblas.a

- name: install CBLAS
  shell: ar -x libcblas.a && gfortran -lopenblas -shared -o libcblas.so *.o && cp libcblas.* /usr/local/lib/ && ldconfig
         chdir=/home/ipython/src/CBLAS/lib
         creates=/usr/local/lib/libcblas.o

- name: Lapack source
  get_url: url=http://www.netlib.org/lapack/lapack-{{ lapack_version }}.tgz
           dest=/home/ipython/src

- name: decompress Lapack
  command: tar -xvzf lapack-{{ lapack_version }}.tgz
           chdir=/home/ipython/src
           creates=/home/ipython/src/lapack-{{ lapack_version }}

- name: config Lapack
  copy: src=lapack-make.inc
        dest=/home/ipython/src/lapack-{{ lapack_version }}/make.inc

- name: make Lapack
  command: make lapacklib
           chdir=/home/ipython/src/lapack-{{ lapack_version }}
           creates=/home/ipython/src/lapack-{{ lapack_version }}/liblapack.a

- name: Install Lapack
  shell: ar -x liblapack.a && gfortran -lopenblas -lcblas -shared -o liblapack.so *.o  && cp liblapack.* /usr/local/lib
         chdir=/home/ipython/src/lapack-{{ lapack_version }}
         creates=/usr/local/lib/liblapack.so

- name: Numpy source
  get_url: url=https://pypi.python.org/packages/source/n/numpy/numpy-{{ numpy_version }}.tar.gz
           dest=/home/ipython/src/

- name: Decompress Numpy
  command: tar -xvzf numpy-{{ numpy_version }}.tar.gz
           chdir=/home/ipython/src
           creates=/home/ipython/src/numpy-{{ numpy_version }}

- name: Configure Numpy
  copy: src=numpy-site.cfg
        dest=/home/ipython/src/numpy-{{ numpy_version }}/site.cfg

- name: Build Numpy
  command: /home/ipython/bin/python setup.py build
           chdir=/home/ipython/src/numpy-{{ numpy_version }}
           creates=/home/ipython/src/numpy-{{ numpy_version }}/build

- name: Install Numpy
  command: /home/ipython/bin/python setup.py install
           chdir=/home/ipython/src/numpy-{{ numpy_version }}
           creates=/home/ipython/bin/f2py

- name: Scipy source
  get_url: url=https://pypi.python.org/packages/source/s/scipy/scipy-{{ scipy_version }}.tar.gz
           dest=/home/ipython/src/

- name: Decompress Scipy
  command: tar -xvzf scipy-{{ scipy_version }}.tar.gz
           chdir=/home/ipython/src/
           creates=/home/ipython/src/scipy-{{ scipy_version }}

- name: Scipy deps
  apt: pkg=libatlas-base-dev

- name: Cheating with liblapack_atlas
  file: src={{ item.src }} dest={{ item.dest }} state=link
  with_items:
      - src: /usr/lib/atlas-base/atlas/liblapack.a
        dest: /usr/local/lib/liblapack_atlas.a
      - src: /usr/lib/atlas-base/atlas/liblapack.so
        dest: /usr/local/lib/liblapack_atlas.so

- name: Configure Scipy
  copy: src=scipy-site.cfg
        dest=/home/ipython/src/scipy-{{ scipy_version }}/site.cfg

- name: Build Scipy
  command: /home/ipython/bin/python setup.py build
           chdir=/home/ipython/src/scipy-{{ scipy_version }}
           creates=/home/ipython/src/scipy-{{ scipy_version }}/build

- name: Install Scipy
  command: /home/ipython/bin/python setup.py install
           chdir=/home/ipython/src/scipy-{{ scipy_version }}

- name: ipython requirements
  template: src=requirements.txt.j2 dest=/home/ipython/requirements.txt

#- name: Clean build folder
  #file: path=/home/ipython/build
        #state=absent

- name: installing ipython
  pip: chdir=/home/ipython
       requirements=requirements.txt
       virtualenv=/home/ipython

- name: installing matplotlib
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name=matplotlib
       version="{{ matplotlib_version }}"

- name: installing pandas
  when: ipython_pandas
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name=pandas
       version="{{ pandas_version }}"

- name: Installing Scikit-Learn
  when: ipython_learnkit
  pip:  chdir=/home/ipython
        virtualenv=/home/ipython
        name=scikit-learn
        version="{{ sklearn_version }}"

- include: llvm.yml

- name: Installing Numba
  when: ipython_numba
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name={{ item }}
  with_items:
      - numba

- include: numexpr.yml
  when: ipython_numexpr

- name: Installing Theano
  when: ipython_theano
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name=theano

- name: Installing Scikit-Image
  when: ipython_imagesk
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name={{ item}}
  with_items:
      - cython
      - pillow
      - scikit-image

- name: download Blaze
  get_url: url=https://codeload.github.com/ContinuumIO/blaze/tar.gz/{{ blaze_version }}
           dest=/home/ipython/src/blaze-{{ blaze_version }}.tar.gz

- name: Blaze source
  command: tar -xvzf blaze-{{ blaze_version }}.tar.gz
           chdir=/home/ipython/src
           creates=/home/ipython/src/blaze-{{ blaze_version }}

- name: Blaze install
  pip: chdir=/home/ipython/src/blaze-{{ blaze_version }}
       virtualenv=/home/ipython
       name=.


- name: Blosc
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name={{ item}}
  with_items:
      - cython
      - blosc
      - bcolz
      - bloscpack

           # cmake
           # cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr/local ..
           #
           # cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPYTHON_PACKAGE_INSTALL_PREFIX=/home/ipython ..

- name: Installing BLZ
  when: ipython_blz
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name=blz

- name: Installing PyMC
  when: ipython_pymc
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name=pymc

- name: Installing Boost
  apt: name=libboost-python-dev

- name: Installing annoy
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name=annoy

- name: Rocksdb
  include: rocksdb.yml
  when: ipython_rocksdb
  tags: db

# Tables deps
# libhdf5-dev

# MPI deps
# openmpi deps
# libopenmpi-dev
# openmpi-bin


# disco deps
# git
# libcmph-dev
#
# https://github.com/discoproject/disco/archive/0.5.1.tar.gz
