---
- name: iPython needs some packages
  apt: pkg={{ item }}
  with_items:
      - libfreetype6-dev
      - libpng12-dev

- name: Scipy needs some packages
  apt: pkg={{ item }}
  with_items:
      # Scipy
      - gfortran
      - libblas-dev
      - liblapack-dev
      - libatlas-dev
  when: ipython_scipy

- name: ipython requirements
  template: src=requirements.txt.j2 dest=/home/ipython/requirements.txt

- name: Clean build folder
  file: path=/home/ipython/build
        state=absent

- name: installing ipython
  pip: chdir=/home/ipython
       requirements=requirements.txt
       virtualenv=/home/ipython

- name: installing numpy
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name=numpy

- name: installing matplotlib
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name=matplotlib

- name: installing scipy
  when: ipython_scipy or ipython_pandas
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name=scipy
- name: installing pandas
  when: ipython_pandas
  pip: chdir=/home/ipython
       virtualenv=/home/ipython
       name=pandas

